config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "search/index"
  post "search", to: "search#index"
  get "search_history", to: "home#search_history"
  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"
  get "product_details/:product_id/:gl", to: "home#product_details", as: :product_details
  get "comparisons/:product_id", to: "comparisons#show", as: "show_comparison"  
  get "comparisons/:product_id/comparison", to: "comparisons#comparison", as: "detailed_comparison"
  get "product_details/:product_id/:gl/forecast", to: "home#forecast", as: "product_forecast"
  post 'predictions/create', to: 'predictions#create'


authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => "/sidekiq"

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:search_history]
  protect_from_forgery except: :forecast 

  def index
  end

  def terms
  end

  def privacy
  end

  def search_history
    @unique_products = current_user.search_results.select('distinct on (product_id, gl) product_id, gl, title').order(:product_id, :gl)
  end

  def product_details
    @product_id = params[:product_id]
    @gl = params[:gl]
    results_scope = current_user.search_results.where(product_id: @product_id, gl: @gl)
  
    if params[:start_date].present? && params[:end_date].present?
      @start_date = Date.parse(params[:start_date])
      @end_date = Date.parse(params[:end_date])
      results_scope = results_scope.where(date: @start_date..@end_date)
  
      extracted_total_prices = results_scope.pluck(:extracted_total_price)
      @average_price = extracted_total_prices.sum / extracted_total_prices.size unless extracted_total_prices.empty?
    end
  
    @search_results = results_scope.order(date: :desc)
    @chart_data = results_scope.group_by_day(:date).average(:extracted_total_price).map do |date, price|
      [date.strftime("%Y-%m-%d"), price]
    end.to_h

    if @chart_data.values.any?
      min_price = @chart_data.values&.compact_blank&.min
      max_price = @chart_data.values&.compact_blank&.max
      @min_chart_value = min_price * 0.95
      @max_chart_value = max_price * 1.05
    end
  end

  def forecast
    @product_id = params[:product_id]
    @gl = params[:gl]
    results_scope = current_user.search_results.where(product_id: @product_id, gl: @gl)
  
    historical_data = results_scope.group_by_day(:date).average(:extracted_total_price).map do |date, price|
      [date.strftime("%Y-%m-%d"), price]
    end.to_h

    @forecast = Prophet.forecast(historical_data, count: 10)
    forecast_data = @forecast.map { |date, price| [date, price] }.to_h

    # Collect actual prices and forecasted prices for error calculation
    actual_prices = historical_data.values.compact
    predicted_prices = forecast_data.values.take(actual_prices.size)

    # Call print_errors to output the error metrics
    print_errors(actual_prices, predicted_prices, 'Prophet', 'Prophet Error Metrics')

    combined_data = {
      historical: historical_data,
      forecast: forecast_data
    }

    all_prices = historical_data.values + forecast_data.values
    @min_chart_value = all_prices.compact_blank.min
    @max_chart_value = all_prices.compact_blank.max

    respond_to do |format|
      format.json { render json: combined_data.merge(min_chart_value: @min_chart_value, max_chart_value: @max_chart_value) }
    end
  end

  private

  def mean_squared_error(actual, predicted)
    sum = 0.0
    actual.zip(predicted).each do |a, p|
      sum += (a - p) ** 2
    end
    sum / actual.size
  end

  def mean_absolute_error(actual, predicted)
    sum = 0.0
    actual.zip(predicted).each do |a, p|
      sum += (a - p).abs
    end
    sum / actual.size
  end

  def print_errors(actual, predicted, model_name, label)
    if actual.size != predicted.size
      puts "Error: Inconsistent data lengths. Actual: #{actual.size}, Predictions: #{predicted.size}"
      return
    end

    puts label
    mse_value = mean_squared_error(actual, predicted)
    rmse_value = Math.sqrt(mse_value)
    mae_value = mean_absolute_error(actual, predicted)
    mape_value = actual.zip(predicted).map { |a, p| (a - p).abs / a.to_f }.sum / actual.size * 100

    puts "MSE: #{mse_value}"
    puts "SQRT(MSE): #{rmse_value}"
    puts "MAE: #{mae_value}"
    puts "RMSE: #{rmse_value}"
    puts "MAPE: #{mape_value}%"
  end
end
# 19:56:36 web.1    | Prophet Error Metrics
# 19:56:36 web.1    | MSE: 138.0417829277792
# 19:56:36 web.1    | SQRT(MSE): 11.749118389384762
# 19:56:36 web.1    | MAE: 11.749118389384762
# 19:56:36 web.1    | RMSE: 11.749118389384762
# 19:56:36 web.1    | MAPE: 1.7005526688934378%

# LSTM Error Metrics
# MSE: 29.646115680972354
# Sqrt(MSE): 5.44482466944275
# MAE: 5.090996093750005
# RMSE: 5.44482466944275
# MAPE: 0.7372568938186335%

# GRU Error Metrics
# MSE: 25.227700060758742
# Sqrt(MSE): 5.022718393535391
# MAE: 4.730852050781254
# RMSE: 5.022718393535391
# MAPE: 0.7216229761131097%

# SARIMAX Error Metrics
# MSE: 80.27217795262621
# Sqrt(MSE): 8.959474200678644
# MAE: 8.285078447572596
# RMSE: 8.959474200678644
# MAPE: 1.1688290265020849%

app/views/home/index.html.erb
<h1>Welcome to Price comparison and prediction system!</h1>
<%# <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p> %>
<% if user_signed_in? %>
  <%= render 'search/search_form' %>
<% end %>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/product_details.html.erb
<div class="container my-4">
  <h2>Details for Product ID: <%= @product_id %></h2>
  <h3>Located in: <%= @gl.upcase %></h3>

  <%= form_with(url: product_details_path(product_id: @product_id, gl: @gl), method: :get, local: true, class: 'mb-3') do |form| %>
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <%= form.label :start_date, "Start Date:", class: "col-form-label" %>
        <%= form.date_field :start_date, max: Date.today.to_s, value: params[:start_date], class: "form-control" %>
      </div>
      <div class="col-auto">
        <%= form.label :end_date, "End Date:", class: "col-form-label" %>
        <%= form.date_field :end_date, max: Date.today.to_s, value: params[:end_date], class: "form-control" %>
      </div>
      <div class="col-auto">
        <%= form.submit "Filter", class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>

  <%= link_to 'Compare Prices', show_comparison_path(@product_id), class: 'btn btn-info' %>
  <%= button_tag 'Prophet Forecast', type: 'button', data: {controller: "forecast", action: "click->forecast#updateGraph", forecast_url_value: product_forecast_path(@product_id, @gl)},  class: 'btn btn-success' %>

  <%= button_tag 'LSTM Forecast', type: 'button', class: 'btn btn-secondary', onclick: "requestForecast('lstm')" %>
  <%= button_tag 'GRU Forecast', type: 'button', class: 'btn btn-secondary', onclick: "requestForecast('gru')" %>
  <%= button_tag 'SARIMAX Forecast', type: 'button', class: 'btn btn-secondary', onclick: "requestForecast('sarimax')" %>

  <%= line_chart @chart_data, xtitle: 'Date', ytitle: 'Average Price', id: 'price_chart', min: @min_chart_value, max: @max_chart_value %>

  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Price</th>
        <th>Link</th>
        <th>Source</th>
      </tr>
    </thead>
    <tbody>
      <% @search_results.each do |result| %>
        <tr>
          <td><%= result.date.strftime("%Y-%m-%d") %></td>
          <td><%= result.total_price %></td>
          <td><%= link_to 'Link', result.link if result.link.present? %></td>
          <td><%= result.json_data&.dig("merchant", "name") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  function requestForecast(method) {
    const url = `http://127.0.0.1:5000/predict/${method}`; 
    const historicalData = <%=@chart_data.to_json.html_safe%>; 

    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest'
      },
      body: JSON.stringify({series: historicalData}),
      credentials: 'same-origin' 
    })
    .then(response => response.json())
    .then(forecastData => {
      console.log("Forecast data received:", forecastData);
      updateChart('price_chart', historicalData, forecastData);
    })
    .catch(error => console.error('Error:', error));
  }

function updateChart(chartId, historicalData, forecastData) {
    var chart = Chartkick.charts[chartId];
    if (chart) {
        
        let updatedData = [
            {name: "Historical", data: historicalData, color: "#3366CC"},
            {name: "Forecast", data: forecastData, color: "#D9534F"}
        ];
        chart.updateData(updatedData);
    } else {
        console.error("Chart not found: ", chartId);
    }
}

</script>

app/views/home/search_history.html.erb
<div class="container my-4">
  <h2>Search History</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Product ID</th>
        <th scope="col">Title</th>
        <th scope="col">GL</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @unique_products.each do |product| %>
        <tr>
          <td><%= product.product_id %></td>
          <td><%= product.title %></td>
          <td><%= product.gl %></td>
          <td><%= link_to 'View Details', product_details_path(product_id: product.product_id, gl: product.gl), class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>